apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: crtd
data:
  API_BASE_URL: "/api"
  PAYMENTS_BASE_URL: "/api/payments"
  GOOGLE_CLIENT_ID: "864386366829-llpoggv3h5i3osjep8puh2f4llpsslql.apps.googleusercontent.com"