apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crtd
type: Opaque
data:
  POSTGRES_USER: "Y3J0ZF93eXJlZmxvdw=="
  POSTGRES_PASSWORD: "UVhxMkBxQDQ0Q2Ei"
  POSTGRES_DB: "Y3J0ZF93eXJlZmxvdw=="