---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: crtd
spec:
  encryptedData:
    REDIS_PASSWORD: AgAxUN0bPEFWOTU4Bc7/z0r7KbH+nRYByTwjVSeCgOvZO/9B/FNGYtQO3MtTP3Asqq4raG+CkdVNx7K62wxiUWcyVq7ni5w28+Dgj2sfhxjrdZkTiI8uoqKeaf32Bt1dD8rGClCPmXpk5+iJ+EB3Kq9RzCa7mUsCT6fkF7cE3yWdTJ4BzSpPlx1aKLm8KFnPA14HLA/rp8Fn3SAPCBvcp2zzC4yvY3MLRCXou6wyYqjHmumH5tn0i5Hnhd41R64NMz71NSeKJ5XGUVC8m4gvERMbOfht0BWTjn+l8PuaDU9AIwER6Gt7pLueNrwmTuIFRQWcnO6i+vjDn13qF4vU9PXMG+dByo5VQZmmTHuxCwnD+Ohiy1QB8z/IdwVbhfMijrjQh++C0PqNVEZ+sSYssJIMlUd1uWuoLNhYC4T8z8LrhV8F/OJDsxENj17YZa7zmw+bBYWfqC050ZFGBBcfy3A9o6xdB1MeCFQdnRduUzWam2ZAPFADgQOEb/5CV7FsMyXrtU67s8FWxKb5Pn0NVrf2rTJ/q3RM+iFfdOw6wU/cvSVNslhxsHjHPyFHzsAfCwEmu30nH3DgkyrxIcYrUP4n3I4mK6kJdLy++dRuI4h7IEHv2t+e553hRelvh0LpdWvw9LzQKnei0nVGYkUMqhGmOeYFg7dLiyYbp2iwO09Flq1JXkmy7W0ynO7b6grH+tgVEt+0LtHaYdYNhmw=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: crtd
    type: Opaque
